### ISSUE TITLE
draw_area - library should allow for custom canvas widths in css

### ISSUE THREAD

**Issue by rdmccann** [jordwms/DesignFramework#7]
The draw_area library should not impose the limitation of requiring the canvas to have width= 100%

--It should be able to deal with custom widths set by css.--

**Comment by jordwms** [comment]
Canvas width will always be set to 100% however the canvas container can be set to any size.

**Comment by rdmccann** [comment]
Modified Issue to address what happens when resizing content drawn in the canvas
